arximboldi/lager

- CMakeLists.txt
- test/CMakeLists.txt
This is a first step towards a more modular build, where you can skip the examples, tests and the debugger to get the core lib running with minimal effort.
> Modular build

- lager/context.hpp
- lager/store.hpp
- test/core.cpp
This PR adds support for the `context` (and as such, also `effect`) to spuport multiple different action types. This can be specified with the `lager::actions<...>` tag. These can be multiple types that are convertible from the parent action type, usually a form of variant. Note that the store still can only have a single action type.
```cpp
struct action_A {};
struct action_B {};
struct action_C {};
using any_action = std::variant<action_A, action_B, action_C>>;
void some_effect(lager::context<lager::actions<action_A, action_B>> ctx)
{
if (...)
ctx.dispatch(action_A{});
else
ctx.dispatch(action_B{});
}
void other_effect(context<any_action> ctx)
{
some_effect(ctx);
...
}
```
> Multi action context

- README.rst
When I tried to use this library as header only it did not compile. The file config.hpp was missing. I figured out that if I run cmake as describe in the commit the according file got generated. So I thouhgt this should be reflected in the documentation.
If there is any other way to get the config.hpp generated please let me know.
> add cmake configure step in readme for header only usage

- lager/deps.hpp
- lager/event_loop/sdl.hpp
`deps.hpp` uses [`std::runtime_error`](https://en.cppreference.com/w/cpp/error/runtime_error) which is defined in `<stdexcept>`,
and `sdl.hpp` uses [`std::min`](https://en.cppreference.com/w/cpp/algorithm/min) which is defined in `<algorithm>`.
Both should be explicitly imported.
> add missing includes to deps.hpp and event_loop/sdl.hpp

- doc/architecture.rst
- doc/cursors.rst
- doc/modularity.rst
- doc/views.rst
- example/autopong/main.cpp
- example/counter/ncurses/main.cpp
- example/counter/sdl2/main.cpp
- example/counter/std/main.cpp
- lager/context.hpp
- lager/debug/debugger.hpp
- lager/debug/tree_debugger.hpp
- lager/deps.hpp
- lager/detail/nodes.hpp
- lager/event_loop/manual.hpp
- lager/reader.hpp
- lager/store.hpp
- lager/util.hpp
- test/core.cpp
- test/debug.cpp
This makes the `lager::store` be a `reader` kind of cursor. This simplifies the API: we do not need a view function, we can just `watch` the store itself. Also, we get some niceties, since watching a cursor is more versatile (we also get the previous value) and of course, we can use derived cursors to provide views for sub-sections of the model, etc.
It is an open question whether it would be interesting to make it also a `writer` kind of cursor. This could be added with a `with_writeable()` enhancer that adds a `lager::replace_state_action` (it is dispatched on `set()`) and somewhat makes the store a full cursor. Note that we need the action to avoid problems wrt. time-travelling debugging. Anyways, this may present conceptual problems and add too much temptation to just avoid actions, …
> Redux cursors

- doc/effects.rst
- doc/model.rst
Also it's usually called "database" not "data-base". Should I change that too?
I've seen "datastore" and "data store" being used online. Firefox thinks "datastore" is a typo.
> Fix typos in online docs (model.rst)

- lager/state.hpp
From cpp ref:
> Including <iostream> behaves as if it defines a static storage duration object of type std::ios_base::Init, whose constructor initializes the standard stream objects if it is the first std::ios_base::Init object to be constructed, and whose destructor flushes those objects (except for cin and wcin) if it is the last std::ios_base::Init object to be destroyed.
It seems this probably slipped in while debugging, but including `iostream` in a public header isn't necessarily such a great idea for the above reason.
> state: remove superfluous header

- CMakeLists.txt
- example/counter/ncurses/main.cpp
- lager/event_loop/boost_asio.hpp
- lager/store.hpp
- test/event_loop/boost_asio.cpp
- test/xformed.cpp
This allows using a strand on top of a multi-threaded context.
> Boost Asio event loop executor based

- lager/detail/xform_nodes.hpp
- lager/extra/qt.hpp
Also includes a fix for a noisy warning seen with VS2019
> Work around VS2019 bug for scope of send down

- CMakeLists.txt
- lager/context.hpp
- lager/debug/tree_debugger.hpp
- lager/deps.hpp
- lager/util.hpp
- shell.nix
- test/core.cpp
- test/errors.cpp
This branch improves error messages by making `context` and `effect` SFINAE friendly and adding a new `result` type with some static asserts to detect bad signatures in reducers.
> Better error messages

- lager/cursor.hpp
- lager/reader.hpp
- lager/watch.hpp
- lager/writer.hpp
- lager/xform.hpp
- test/watchers.cpp
When you watch a cursor, connection will be logically maintained with
whatever underlying cursor it is associated to.
Note that when you change the cursor, the watcher is not emitted.  The
reason is that this may cause problems if watchers are expected to be
called in a specific time of the event loop (e.g. whenever committing
states or other roots is actually done).  Normally whoever assigns the
cursor assignment has all the information available anyways to perform
the notification themselves, if necessary at all.
Fixes #34 and #33
> Make cursors watchers independent of the underlying node

- lager/event_loop/qml.hpp
This event loop ensures that when an action is dispatched in the main
thread, it is processed it is processed before rendering the next
frame.
The easiest way to use this is to expose a QML type that inhertis from
`event_loop_quick_item`.  This can be your root view model, which also
holds the store or a reference to it.
FYI @Siapran
> Add QML based event loop

- BUILD
- example/autopong/sdl2/main.cpp
- example/counter/ncurses/main.cpp
- example/counter/sdl2/main.cpp
- example/counter/std/main.cpp
- example/snake/qml/main.cpp
- lager/constant.hpp
- lager/debug/debugger.hpp
- lager/debug/http_server.hpp
- lager/detail/lens_nodes.hpp
- lager/detail/nodes.hpp
- lager/detail/signal.hpp
- lager/extra/qt.hpp
- lager/sensor.hpp
- lager/state.hpp
- lager/store.hpp
- lager/watch.hpp
- lager/with.hpp
- shell.nix
- test/core.cpp
- test/debug.cpp
- test/detail/nodes.cpp
- test/sensor.cpp
- test/state.cpp
- test/watchers.cpp
First, we use our own signal implementation instead of boost signals2.
**Warning:** API breaking change! The previous value is not passed to watchers anymore. This is easy to workaround if needed though:
```cpp
data.watch([last=data.get()](auto&& curr) {
// ...
last = curr;
});
```
> Make watching infrastructure more light weight

- lager/lenses/at.hpp
- lager/lenses/at_or.hpp
- lager/lenses/attr.hpp
- lager/lenses/optional.hpp
- lager/lenses/tuple.hpp
- lager/lenses/unbox.hpp
- lager/lenses/variant.hpp
- test/lenses.cpp
This branch introduces four new lens generators for working with tuples:
* `zip` aka: `Lens<W1, P1>, ..., Lens<Wn, Pn> -> Lens<(W1, ..., Wn), (P1, ..., Pn)>`
* `fan` aka: `Lens<W, P1>, ..., Lens<W, Pn> -> Lens<W, (P1, ..., Pn)>`
* `attr` with multiple non-overlapping members
* `element<N>`, `first` and `second`, for accessing the Nth element of a tuple-like value.
> Introduce tuple lenses

- lager/detail/nodes.hpp
- test/cursor.cpp
See issue #62.
I opted for the stateful approach. This fix might not be completely exhaustive, as discussed before, but it will at least stop this particular crash from happening in some projects.
We still advise against using the `lager::automatic_tag` for most cases.
> Fix list of child nodes shrinking during iteration (issue #62)

- lager/event_loop/boost_asio.hpp
- lager/event_loop/manual.hpp
- lager/event_loop/qml.hpp
- lager/event_loop/qt.hpp
- lager/event_loop/queue.hpp
- lager/event_loop/sdl.hpp
When compiling with clang-9 I got this error:
```
..../lager/lager/event_loop/manual.hpp:25:31: error: expected ';' after
expression
throw std::logic_error{"manual_event_loop does not support async()"};
```
adding
```
#include <stdexcept>
```
in manual.hpp fixed the problem.
Then i moved on and added missing includes to all header files inside the event_loop folder :smile: .
> add missing includes

- lager/debug/debugger.hpp
If we include cursor.hpp before debugger.hpp, the compiler will think `cursor` is a template in the expression `m.cursor < m.history.size()` and refuse to compile correctly.
This PR fixes this problem.
```bash
] echo -e '#include <lager/cursor.hpp>\n#include <lager/debug/debugger.hpp>\nint main(){}' > dummy.cpp
] c++ -I<*omitted*> -std=c++17 dummy.cpp
In file included from dummy.cpp:2:
./lager/debug/debugger.hpp: In lambda function:
./lager/debug/debugger.hpp:139:51: error: type/value mismatch at argument 1 in template parameter list for ‘template<class T> class lager::cursor’
139 |                     if (m.cursor < m.history.size())
|                                                   ^
./lager/debug/debugger.hpp:139:51: note:   expected a type, got ‘m.history.size()’
```
> Prevent compiler from treating cursor as template in debugger.hpp

- lager/detail/nodes.hpp
In one of our projects @ Globus Medical I have a compilation error that `remove_if` (line 225) is an unknown identifier.
> Add a missing include in detail/nodes.hpp

- doc/architecture.rst
- doc/cursors.rst
- doc/modularity.rst
- example/autopong/sdl2/main.cpp
- example/counter/ncurses/main.cpp
- example/counter/sdl2/main.cpp
- example/counter/std/main.cpp
- example/snake/qml/main.cpp
- example/todo/imgui/main.cpp
- lager/store.hpp
- test/core.cpp
- test/debug.cpp
- test/event_loop/boost_asio.cpp
- test/event_loop/qml.cpp
- test/event_loop/qt.cpp
- test/event_loop/queue.cpp
- test/event_loop/safe_queue.cpp
- test/setter.cpp
The convention is to have a reducer `update` that can be found via ADL in the model namespace.
> Make reducers optional to make_store

- lager/extra/qt.hpp
The Qt MOC compiler is notoriously slow when preprocessing.
In particular, each time code includes lager/extra/qt.hpp, the MOC compiler spends about four seconds on precompiling it, even though the Qt relevant code is less than 100 lines.
Simply excluding non-Qt relevant code in lager/extra/qt.hpp as follows would reduce MOC processing time to a fraction of a second:
#ifndef Q_MOC_RUN
#include <lager/cursor.hpp>
#include <lager/reader.hpp>
#include <lager/watch.hpp>
#endif
> #108: Reduce Qt MOC compilation time

- lager/context.hpp
- lager/sensor.hpp
`std::result_of<>` has been deprecated in C++17 and removed in C++20
> Change std::result_of<> for std::invoke_result<>

- lager/event_loop/sdl.hpp
Should the `SDL.h` include path be replaced with `SDL2/SDL.h`?
> Use full SDL2 include path

- BUILD
- WORKSPACE
- lager/extra/derive.hpp
- lager/extra/derive/cereal.hpp
- lager/extra/derive/eq.hpp
- lager/extra/derive/hana.hpp
- lager/extra/derive/hash.hpp
- lager/extra/struct.hpp
- test/extra/derive.cpp
Finally! This is something I've been meaning to do for a while and that is useful in quite a few of the production systems currently using Lager. One way to think about it is as a dirty Haskell `deriving()` clause.
This branch adds a series of `LAGER_DERIVE`, `LAGER_DERIVE_TEMPLATE` and `LAGER_DERIVE_NESTED` macros that provide some generic infrastructure for generating code for structs using the Boost.Processor library. This generalizes the mechanisms previously included in `LAGER_STRUCT` friends. The generators are extendable, for now the following are provided:
- **EQ**: generates `operator==` and `operator!=`
- **HANA**: turns the struct into a Boost.Hana sequence... a glorified `BOOST_HANA_ADAPT_STRUCT`.
- **CEREAL**: generates serialization using Cereal, without going through …
> Struct derive macros

- lager/detail/lens_nodes.hpp
- test/cursor.cpp
- test/lenses.cpp
It breaks applying a lens expression over the result of .with() expression.
> Fix unpacking the of nodes in lens reader nodes

- lager/state.hpp
- test/state.cpp
It is possible to assign a state with the new value, which implicitly
creates a new state and replaces the current one. It basically detaches
all the cursors and listeners.
Alternatively, the problem can be solved by making the constructor
explicit, but it may create some inconviniences when using the state.
fixes #135
> Delete ambiguous assigment operators in `state`

- lager/store.hpp
- test/core.cpp
This was causing a weird binding error in clang on the `reducer` capture of the inner lambda when the enhancer is passed an lvalue.
> Forward reducer in with_reducer enhancer

- lager/extra/derive/hash.hpp
This caused issues when attempting to use the generated hashes with standard containers.
> Add const qualification to HASH implementation.

- example/counter/ncurses/terminal.hpp
- lager/debug/http_server.hpp
This is a draft PR for #140
- Because lager is header only, a low footprint implementation that meets current requirements has been in mind.
- There is no dependency on [libhttpserver](https://github.com/etr/libhttpserver) anymore but cmake and nix files need modification.
- If windows support is required, manipulation of `resources_path` should be different.
- Currently, there are no unit tests for http_debug_server, we need some idea of how it should be done.
> Reimplement the lager::http_debug_server using Boost.Beast

- lager/util.hpp
- test/util.cpp
One of the problems of `std::variant` is that it expands all thea lternatives in the type name.  This can lead to humongous compilation errors.  This is particularly true for the patterns encouraged by Lager, where actions are variants of variants of variants...
One solution to erase the alternatives from the type of the variant is to do something of the form:
```c++
using variant_t = std::variant<...>;
struct my_variant : variant_t { using variant_t::variant_t; };
```
However, `std::visit` does not work with variants of that form in some implemnetations.  [This is definitelly true for libstdc++](
https://stackoverflow.com/questions/51309467/using-stdvisit-on-a-class-inheriting-from-stdvariant-libstdc-vs-libc).
This PR works around it in lager::match itself. Also some utilities are …
> Make `lager::match` work with types that are derived from `std::variant`

- lager/extra/cereal/variant_with_name.hpp
- test/cereal/variant_with_name.cpp
As added later in cereal/types/variant.hpp (see e6dc5d37)
> Support monostate variant serialization

- CMakeLists.txt
- cmake/icm_build_failure_testing.cmake
- lager/cursor.hpp
- lager/reader.hpp
- lager/watch.hpp
- lager/with.hpp
- test/CMakeLists.txt
- test/build_failure/CMakeLists.txt
- test/build_failure/cursor-to-cursor.cpp
- test/build_failure/cursor-to-reader.cpp
- test/build_failure/lense-to-cursor.cpp
- test/build_failure/lense-to-reader.cpp
- test/build_failure/map-to-reader.cpp
- test/build_failure/reader-to-reader.cpp
- test/build_failure/setup.hpp
- test/build_failure/with-to-reader.cpp
- test/build_failure/xform-to-cursor.cpp
- test/build_failure/xform-to-reader.cpp
Lager offers a lot of assignment and implicit conversion facilities. However, in many cases, bad assignment operations are not catched by language servers and the compilation error messages can be rather opaque, sometimes failing to point out the offending line to the user. The following examples are illustrative:
https://godbolt.org/z/cGMsY7Ghq
This PR aims to improve the situation through the use of sfinae on certain implicit conversion operators and chosen ctors.
Under the proposed changes, a bad assignment statement compiling in GCC will produce something like:
```
/home/foouser/project/lager/test/compilation/map_to_reader.cpp: In function ‘int main()’: …
```
> Nicer build failure messages on bad assignments

- lager/watch.hpp
- test/watchers.cpp
It turned out that there was no way to unbind anything from a reader after once bound. Assignment operator keeps all the binding untouched (which looks a bit strange, but "by design"), so we need a separate method to unbind everything when needed.
> Implement watchable_base::unbind()

- lager/lenses/at.hpp
This allows us to create a cursor to an `immer::table` element i.e.
```c++
struct item { int id; }
struct model {
immer::table<item> items;
};
...
lager::reader<item> item_123 = store[&model::items][123].zoom(lager::lenses::or_default);
```
This is currently a compile error because `immer::table` has no `set` operation, so the first implementation of `at_setter_impl` would be selected leading to the invalid assignment.
> Impl. an "at setter" that works with immer::table

- nix/deps.nix
- fix the `cmakeFlags` specification for cereal, as it must be a string (and not a simple string)
- build immer and zug explicitly disabling tests and examples, as they are neither run nor installed
> nix: fix build of dependencies

- example/CMakeLists.txt
The right variable for requesting the unicode version of curses is `CURSES_NEED_WIDE`, not `CMAKE_CURSES_NEED_WIDE` [1].
[1] https://cmake.org/cmake/help/latest/module/FindCurses.html
> cmake: fix finding cursesw

- lager/event_loop/sdl.hpp
This way it builds also with GCC 13, which no more implicitly includes `<cstdint>` from other headers included in this file.
> Include <cstdint> for std::uint32_t

- doc/CMakeLists.txt
- example/CMakeLists.txt
This makes things rely less on their current relative locations in the sources.
> cmake: use ${CMAKE_CURRENT_SOURCE_DIR} where possible

- lager/debug/http_server.hpp
Boost Beast 1.80 switches from `boost::string_view` to `boost::core::string_view` [1][2], and thus the `to_string()` method to convert to `std::string` is not available anymore.
Both the old and the new `string_view` types used support converting to `std::string` via operator, hence switch to a `static_cast` to do the conversion. This supports building with all the versions of boost.
[1] https://www.boost.org/doc/libs/release/libs/beast/doc/html/beast/release_notes.html
[2] https://github.com/boostorg/beast/issues/2417
> Fix build of http_debug_server with boost >= 1.80

- default.nix
- lager/lenses/at.hpp
- lager/lenses/at_or.hpp
- lager/reader.hpp
- lager/writer.hpp
- shell.nix
This allows better integration with emscriten
> Fix at_or when no exception support

- lager/config.hpp
- lager/store.hpp
Addresses (some?) of the issues raised in #126 .
> MSVC: Fixes

- lager/detail/nodes.hpp
- lager/reader.hpp
- test/cursor.cpp
This commit enables the forward declaration of a type held by a reader without any new memory allocation or virtual methods. This is achieved by creating a new class  -- observable_reader_node -- in the reader_node hierarchy which acts as a view for the type held by reader_node.
Performance Impact
Ad-hoc benchmarks (i.e. not in commit) were performed with nanobench. (https://nanobench.ankerl.com/index.html)
Compared to baseline, the impact on a reader get method was non-existent. The same was true for map. The impact on watch seemingly ranged from indiscernible to rather small, i.e. in the order of 0.5-1.5%, although why there even is an impact isn't clear.
Downsides and Limitations
1. If it matters, the protected keyword has now been introduced within the reader node class hierarchy. …
> allow forward declaration of values held by reader

- CMakeLists.txt
- lager/config.hpp
Fixes https://github.com/arximboldi/lager/issues/204
Downstream: https://lily-is.land/kazv/kazv/-/merge_requests/104
> Allow the user to always enable or disable exceptions

- lager/detail/nodes.hpp
This commit fixes an issue where the observable_reader_node, which serve as a base class for reader_node, didn't have a virtual dtor.
This was made easier to miss in virtue of observable_reader_node not having any virtual method.
By having observable_reader_node derive from reader_node_base, we effectively fix the issue and by removing multiple inheritance. observable_reader_node now inherits its virtual dtor from reader_node_base.
> fix missing virtual dtor on observable_reader_node

- lager/detail/nodes.hpp
This fixes an issue in which calls to link occurring during notification would invalidate the iterators of the structured for loop. Calling link as a result of a reader<T>::watch callback can occur quite naturally.
By using the size of the children vector at the point at which the for loop is initiated, and by using the [] operator in order to access the children within the vector, the issue is avoided.
> revert to index based notify loop

- lager/detail/nodes.hpp
I spent two whole days wondering why my application crashes all of a sudden. Hope this can prevent someone changing it back to ranged-for in the future, as it is really tempting to do so.
> Add a comment to explain why ranged-for cannot be used

- lager/lenses/optional.hpp
- test/lenses.cpp
fix for #215.
also fixes a couple potential use-after-move issues.
> Enable writing to force_opt lens with non-opt value.

- lager/extra/thunk.hpp
- test/extra/thunk.cpp
This adds a new enhancer called `with_thunk`, which enables dispatching not only plain actions but also thunk functions that take a `lager::context`.
This allows deferring logic such as conditional dispatch or side effects until runtime, similar to what redux-thunk provides in Redux.
Example usage:
```C++
store.dispatch([](lager::context<action> ctx) {
// perform some effectful logic, then dispatch
ctx.dispatch(some_action{});
});
```
> Add with_thunk enhancer for thunk-style dispatch
