arximboldi/lager

lager/deps.hpp, test/deps.cpp
Due to implementation details, we now also do not provide the chance
of converting from ref to non-ref dependencies when passing
depedencies around.  This new behavior might actually be less
confusing anyways.
=> Add indirectly provided dependencies via a function

lager/event_loop/qapplication.hpp
I implemented this while creating a QML example using the `lager::store`. I'll commit the example in a separate PR.
=> qapplication: add event loop implementation

example/CMakeLists.txt, example/snake/model.cpp, example/snake/model.hpp, example/snake/qml/main.cpp, example/snake/qml/main.qml, example/snake/qml/qmodel.cpp, example/snake/qml/qmodel.hpp
- demonstrate how to use the lager::store with qt/qml
=> example: add snake example

lager/context.hpp, lager/deps.hpp, lager/store.hpp
This lib did not compile because of a missing include to memory.
=> missing include to <memory>

example/snake/qml/main.cpp, example/todo/todo.cpp, lager/event_loop/qt.hpp, lager/util.hpp
This makes it easier to instantiate a store from different places.
=> Make Qt event loop a bit more generic

README.rst, doc/cursor.rst, doc/doxygen.config, doc/event_loop.rst, doc/index.rst, doc/lens.rst, doc/lenses.rst, doc/views.rst, lager/constant.hpp, lager/cursor.hpp, lager/lens.hpp, lager/lenses.hpp, lager/lenses/at.hpp, lager/lenses/attr.hpp, lager/lenses/optional.hpp, lager/lenses/unbox.hpp, lager/lenses/variant.hpp, lager/reader.hpp, lager/sensor.hpp, lager/state.hpp, lager/with.hpp, lager/writer.hpp
=> Add placeholders for documentation of new modules

BUILD
missing boost intrusive/list.hpp
=> update boost deps

doc/modularity.rst
=> Fix inconsistency between doc and API

lager/cursor.hpp, lager/reader.hpp, lager/watch.hpp, lager/with.hpp, lager/writer.hpp, test/watchers.cpp, test/xformed.cpp
=> Expose map and filter directly in the cursor api

lager/event_loop/sdl.hpp
According to https://emscripten.org/docs/porting/emscripten-runtime-environment.html#browser-main-loop, infinite main loops and functions that never return are problematic when running in the browser and they should be replaced by their async version based on `emscripten_request_animation_frame_loop()`.
This PR adds support for this through `sdl_event_loop.run_async()`.
=> Add async main loop for SDL+Emscripten

doc/cursors.rst
=> Add note to cursor docs about watch and scope

lager/event_loop/sdl.hpp
This seems to improve responsiveness of the page in some scenarios.
=> Sdl event loop improvements for Emscripten

.github/workflows/test.yml, CMakeLists.txt, example/CMakeLists.txt, example/autopong/autopong.cpp, example/counter/ncurses/terminal.hpp, lager/debug/tree_debugger.hpp, lager/extra/cereal/tuple.hpp, lager/lenses/tuple.hpp, nix/deps.nix, shell.nix
This tries to fix builds on MacOS... Should address #145 and more.
@Siapran the lenses code that you wrote seems to be failing on Clang in a very strange way. Can you take a look?
FYI @gracicot
=> Fix shell macos

CMakeLists.txt, default.nix, example/counter/ncurses/terminal.cpp, lager/debug/debugger.hpp, lager/debug/http_server.hpp, nix/deps.nix, shell.nix, test/debug.cpp
=> Http server tweaks

doc/store.rst, lager/extra/derive/hash.hpp, test/extra/derive.cpp
=> Some fixes

lager/event_loop/manual.hpp, lager/event_loop/queue.hpp, lager/event_loop/safe_queue.hpp, test/event_loop/manual.cpp, test/event_loop/queue.cpp, test/event_loop/safe_queue.cpp
=> Fix exception safety of basic event loop queues

lager/detail/access.hpp, lager/reader.hpp, lager/writer.hpp, test/cursor.cpp
=> Throw on access to uninitialized reader/writer

lager/future.hpp
When the promise state is destructed the future would be fullfilled. This could even happen sometimes in the wrong thread, or at completly the wrong time.  It should be ok for a promise to never be fullfilled.
Instead we keep track of fullfillment (`done`) separatelly for immediate chaining.
=> Fix futures would be called on promise destruction causing havoc

doc/effects.rst
=> Minor updates to effects.rst

doc/modularity.rst
fix minor typos modularity.rst
=> fix minor typos modularity.rst

test/CMakeLists.txt
Mistakes were made. :facepalm: 
Wrongfully removed in 9a56535.
=> reintroduce detail/nodes tests

BUILD, lager/util.hpp, test/util.cpp
=> make match constexpr

lager/config.hpp
=> Detect exceptions in a more cross platform manner
